In [3]:
import os
print(os.getcwd())

c:\Users\aitor\Desktop\Proyectos\football-ml\notebooks

In [4]:
import pandas as pd
import pathlib

# Get project root (one level up from notebooks/)
PROJECT_ROOT = pathlib.Path().resolve().parent
data_path = PROJECT_ROOT / "data" / "raw" / "laliga" / "SP1_1314.csv"

df = pd.read_csv(data_path)
print(df.shape)
print(df.columns.tolist())

(380, 67)
['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'SJH', 'SJD', 'SJA', 'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA', 'PSCH', 'PSCD', 'PSCA']

In [6]:
# Key columns explanation
key_columns = {
    "Div": "Division (SP1 = La Liga)",
    "Date": "Match date",
    "HomeTeam": "Home team name",
    "AwayTeam": "Away team name",
    "FTHG": "Full Time Home Goals",
    "FTAG": "Full Time Away Goals",
    "FTR": "Full Time Result (H/D/A)",
    "HTHG": "Half Time Home Goals",
    "HTAG": "Half Time Away Goals",
    "HTR": "Half Time Result",
    "HS": "Home Shots",
    "AS": "Away Shots",
    "HST": "Home Shots on Target",
    "AST": "Away Shots on Target",
    "HF": "Home Fouls",
    "AF": "Away Fouls",
    "HC": "Home Corners",
    "AC": "Away Corners",
    "HY": "Home Yellow cards",
    "AY": "Away Yellow cards",
    "HR": "Home Red cards",
    "AR": "Away Red cards",
    "B365H": "Bet365 odds Home win",
    "B365D": "Bet365 odds Draw",
    "B365A": "Bet365 odds Away win",
}

for col, desc in key_columns.items():
    print(f"{col:10} → {desc}")

Div        → Division (SP1 = La Liga)
Date       → Match date
HomeTeam   → Home team name
AwayTeam   → Away team name
FTHG       → Full Time Home Goals
FTAG       → Full Time Away Goals
FTR        → Full Time Result (H/D/A)
HTHG       → Half Time Home Goals
HTAG       → Half Time Away Goals
HTR        → Half Time Result
HS         → Home Shots
AS         → Away Shots
HST        → Home Shots on Target
AST        → Away Shots on Target
HF         → Home Fouls
AF         → Away Fouls
HC         → Home Corners
AC         → Away Corners
HY         → Home Yellow cards
AY         → Away Yellow cards
HR         → Home Red cards
AR         → Away Red cards
B365H      → Bet365 odds Home win
B365D      → Bet365 odds Draw
B365A      → Bet365 odds Away win

In [9]:
df[["Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "FTR", "B365H", "B365D", "B365A"]].head(10)

       Date     HomeTeam    AwayTeam  FTHG  FTAG FTR  B365H  B365D  B365A
0  17/08/13     Sociedad      Getafe     2     0   H   1.73   3.60   4.75
1  17/08/13     Valencia      Malaga     1     0   H   1.53   4.00   6.00
2  17/08/13   Valladolid  Ath Bilbao     1     2   A   2.50   3.30   2.80
3  18/08/13    Barcelona     Levante     7     0   H   1.08  10.00  26.00
4  18/08/13      Osasuna     Granada     1     2   A   2.00   3.30   3.75
5  18/08/13  Real Madrid       Betis     2     1   H   1.17   7.00  17.00
6  18/08/13      Sevilla  Ath Madrid     1     3   A   2.80   3.30   2.50
7  19/08/13      Almeria  Villarreal     2     3   A   2.60   3.20   2.75
8  19/08/13        Celta     Espanol     2     2   D   2.20   3.20   3.40
9  19/08/13    Vallecano       Elche     3     0   H   2.25   3.25   3.25

In [10]:
df[["Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "FTR", "B365H", "B365D", "B365A"]].tail(10)

         Date     HomeTeam    AwayTeam  FTHG  FTAG FTR  B365H  B365D  B365A
370  16/05/14       Malaga     Levante     1     0   H   1.91   3.40   4.00
371  17/05/14    Barcelona  Ath Madrid     1     1   D   1.85   3.80   4.50
372  17/05/14  Real Madrid     Espanol     3     1   H   1.33   5.00   8.50
373  17/05/14     Valencia       Celta     2     1   H   1.75   3.75   4.50
374  18/05/14      Almeria  Ath Bilbao     0     0   D   2.25   3.40   3.10
375  18/05/14      Osasuna       Betis     2     1   H   1.36   5.00   7.50
376  18/05/14      Sevilla       Elche     3     1   H   1.80   3.75   4.20
377  18/05/14     Sociedad  Villarreal     1     2   A   2.00   3.60   3.50
378  18/05/14   Valladolid     Granada     0     1   A   2.10   3.30   3.50
379  18/05/14    Vallecano      Getafe     1     2   A   4.00   3.10   2.05

In [11]:
# Home advantage analysis
total = len(df)
home_wins = (df["FTR"] == "H").sum()
draws = (df["FTR"] == "D").sum()
away_wins = (df["FTR"] == "A").sum()

print(f"Home wins: {home_wins/total:.1%}")
print(f"Draws:     {draws/total:.1%}")
print(f"Away wins: {away_wins/total:.1%}")

Home wins: 47.1%
Draws:     22.6%
Away wins: 30.3%

In [13]:
# Get all CSV files matching the pattern
csv_files = sorted(PROJECT_ROOT.glob("data/raw/laliga/SP1_*.csv"))

# Load all dataframes
dfs = [pd.read_csv(file) for file in csv_files]

# Check if all have the same columns
columns_match = all(df.columns.equals(dfs[0].columns) for df in dfs)
print(f"All dataframes have same columns: {columns_match}")

if not columns_match:
    print("\nColumns per file:")
for file, df in zip(csv_files, dfs):
    missing = set(dfs[0].columns) - set(df.columns)
    extra = set(df.columns) - set(dfs[0].columns)
    if missing or extra:
        print(f"{file.name}: missing={missing}, extra={extra}")

# Concatenate all dataframes
df_combined = pd.concat(dfs, ignore_index=True)
print(f"\nCombined shape: {df_combined.shape}")
print(f"Date range: {df_combined['Date'].min()} to {df_combined['Date'].max()}")

All dataframes have same columns: False

Columns per file:
SP1_1516.csv: missing={'SJD', 'SJH', 'SJA'}, extra=set()
SP1_1617.csv: missing={'SJD', 'SJH', 'SJA'}, extra=set()
SP1_1718.csv: missing={'SJD', 'SJH', 'SJA'}, extra=set()
SP1_1819.csv: missing={'LBH', 'SJD', 'SJA', 'LBA', 'LBD', 'SJH'}, extra=set()
SP1_1920.csv: missing={'BbAvH', 'BbMxD', 'BbAHh', 'SJA', 'BbAv<2.5', 'BbAvAHH', 'BbAv>2.5', 'SJH', 'BbMx>2.5', 'BbMxAHH', 'BbAvA', 'BbAH', 'BbMxAHA', 'LBD', 'BbMxA', 'LBH', 'BbOU', 'BbMx<2.5', 'SJD', 'BbAvD', 'BbAvAHA', 'LBA', 'Bb1X2', 'BbMxH'}, extra={'MaxH', 'B365>2.5', 'VCCA', 'Avg<2.5', 'B365CA', 'B365AHA', 'IWCH', 'AvgH', 'MaxCA', 'PAHA', 'AHCh', 'AHh', 'BWCA', 'B365C>2.5', 'IWCD', 'PAHH', 'MaxC<2.5', 'Max>2.5', 'MaxCAHA', 'AvgCAHH', 'IWCA', 'MaxCH', 'PCAHA', 'PC<2.5', 'AvgC<2.5', 'VCCH', 'AvgCD', 'MaxD', 'WHCA', 'AvgAHA', 'BWCD', 'Avg>2.5', 'MaxCAHH', 'P>2.5', 'MaxAHH', 'BWCH', 'AvgCH', 'MaxAHA', 'B365CAHH', 'AvgD', 'P<2.5', 'B365CH', 'WHCD', 'Time', 'AvgCA', 'MaxC>2.5', 'AvgCAHA', 'Max<2.5', 'PCAHH', 'MaxA', 'MaxCD', 'B365CD', 'B365AHH', 'B365CAHA', 'AvgC>2.5', 'B365<2.5', 'PC>2.5', 'VCCD', 'WHCH', 'AvgAHH', 'B365C<2.5', 'AvgA'}
SP1_2021.csv: missing={'BbAvH', 'BbMxD', 'BbAHh', 'SJA', 'BbAv<2.5', 'BbAvAHH', 'BbAv>2.5', 'SJH', 'BbMx>2.5', 'BbMxAHH', 'BbAvA', 'BbAH', 'BbMxAHA', 'LBD', 'BbMxA', 'LBH', 'BbOU', 'BbMx<2.5', 'SJD', 'BbAvD', 'BbAvAHA', 'LBA', 'Bb1X2', 'BbMxH'}, extra={'MaxH', 'B365>2.5', 'VCCA', 'Avg<2.5', 'B365CA', 'B365AHA', 'IWCH', 'AvgH', 'MaxCA', 'PAHA', 'AHCh', 'AHh', 'BWCA', 'B365C>2.5', 'IWCD', 'PAHH', 'MaxC<2.5', 'Max>2.5', 'MaxCAHA', 'AvgCAHH', 'IWCA', 'MaxCH', 'PCAHA', 'PC<2.5', 'AvgC<2.5', 'VCCH', 'AvgCD', 'MaxD', 'WHCA', 'AvgAHA', 'BWCD', 'Avg>2.5', 'MaxCAHH', 'P>2.5', 'MaxAHH', 'BWCH', 'AvgCH', 'MaxAHA', 'B365CAHH', 'AvgD', 'P<2.5', 'B365CH', 'WHCD', 'Time', 'AvgCA', 'MaxC>2.5', 'AvgCAHA', 'Max<2.5', 'PCAHH', 'MaxA', 'MaxCD', 'B365CD', 'B365AHH', 'B365CAHA', 'AvgC>2.5', 'B365<2.5', 'PC>2.5', 'VCCD', 'WHCH', 'AvgAHH', 'B365C<2.5', 'AvgA'}
SP1_2122.csv: missing={'BbAvH', 'BbMxD', 'BbAHh', 'SJA', 'BbAv<2.5', 'BbAvAHH', 'BbAv>2.5', 'SJH', 'BbMx>2.5', 'BbMxAHH', 'BbAvA', 'BbAH', 'BbMxAHA', 'LBD', 'BbMxA', 'LBH', 'BbOU', 'BbMx<2.5', 'SJD', 'BbAvD', 'BbAvAHA', 'LBA', 'Bb1X2', 'BbMxH'}, extra={'MaxH', 'B365>2.5', 'VCCA', 'Avg<2.5', 'B365CA', 'B365AHA', 'IWCH', 'AvgH', 'MaxCA', 'PAHA', 'AHCh', 'AHh', 'BWCA', 'B365C>2.5', 'IWCD', 'PAHH', 'MaxC<2.5', 'Max>2.5', 'MaxCAHA', 'AvgCAHH', 'IWCA', 'MaxCH', 'PCAHA', 'PC<2.5', 'AvgC<2.5', 'VCCH', 'AvgCD', 'MaxD', 'WHCA', 'AvgAHA', 'BWCD', 'Avg>2.5', 'MaxCAHH', 'P>2.5', 'MaxAHH', 'BWCH', 'AvgCH', 'MaxAHA', 'B365CAHH', 'AvgD', 'P<2.5', 'B365CH', 'WHCD', 'Time', 'AvgCA', 'MaxC>2.5', 'AvgCAHA', 'Max<2.5', 'PCAHH', 'MaxA', 'MaxCD', 'B365CD', 'B365AHH', 'B365CAHA', 'AvgC>2.5', 'B365<2.5', 'PC>2.5', 'VCCD', 'WHCH', 'AvgAHH', 'B365C<2.5', 'AvgA'}
SP1_2223.csv: missing={'BbAvH', 'BbMxD', 'BbAHh', 'SJA', 'BbAv<2.5', 'BbAvAHH', 'BbAv>2.5', 'SJH', 'BbMx>2.5', 'BbMxAHH', 'BbAvA', 'BbAH', 'BbMxAHA', 'LBD', 'BbMxA', 'LBH', 'BbOU', 'BbMx<2.5', 'SJD', 'BbAvD', 'BbAvAHA', 'LBA', 'Bb1X2', 'BbMxH'}, extra={'MaxH', 'B365>2.5', 'VCCA', 'Avg<2.5', 'B365CA', 'B365AHA', 'IWCH', 'AvgH', 'MaxCA', 'PAHA', 'AHCh', 'AHh', 'BWCA', 'B365C>2.5', 'IWCD', 'PAHH', 'MaxC<2.5', 'Max>2.5', 'MaxCAHA', 'AvgCAHH', 'IWCA', 'MaxCH', 'PCAHA', 'PC<2.5', 'AvgC<2.5', 'VCCH', 'AvgCD', 'MaxD', 'WHCA', 'AvgAHA', 'BWCD', 'Avg>2.5', 'MaxCAHH', 'P>2.5', 'MaxAHH', 'BWCH', 'AvgCH', 'MaxAHA', 'B365CAHH', 'AvgD', 'P<2.5', 'B365CH', 'WHCD', 'Time', 'AvgCA', 'MaxC>2.5', 'AvgCAHA', 'Max<2.5', 'PCAHH', 'MaxA', 'MaxCD', 'B365CD', 'B365AHH', 'B365CAHA', 'AvgC>2.5', 'B365<2.5', 'PC>2.5', 'VCCD', 'WHCH', 'AvgAHH', 'B365C<2.5', 'AvgA'}
SP1_2324.csv: missing={'BbAvH', 'BbMxD', 'BbAHh', 'SJA', 'BbAv<2.5', 'BbAvAHH', 'BbAv>2.5', 'SJH', 'BbMx>2.5', 'BbMxAHH', 'BbAvA', 'BbAH', 'BbMxAHA', 'LBD', 'BbMxA', 'LBH', 'BbOU', 'BbMx<2.5', 'SJD', 'BbAvD', 'BbAvAHA', 'LBA', 'Bb1X2', 'BbMxH'}, extra={'MaxH', 'B365>2.5', 'VCCA', 'Avg<2.5', 'B365CA', 'B365AHA', 'IWCH', 'AvgH', 'MaxCA', 'PAHA', 'AHCh', 'AHh', 'BWCA', 'B365C>2.5', 'IWCD', 'PAHH', 'MaxC<2.5', 'Max>2.5', 'MaxCAHA', 'AvgCAHH', 'IWCA', 'MaxCH', 'PCAHA', 'PC<2.5', 'AvgC<2.5', 'VCCH', 'AvgCD', 'MaxD', 'WHCA', 'AvgAHA', 'BWCD', 'Avg>2.5', 'MaxCAHH', 'P>2.5', 'MaxAHH', 'BWCH', 'AvgCH', 'MaxAHA', 'B365CAHH', 'AvgD', 'P<2.5', 'B365CH', 'WHCD', 'Time', 'AvgCA', 'MaxC>2.5', 'AvgCAHA', 'Max<2.5', 'PCAHH', 'MaxA', 'MaxCD', 'B365CD', 'B365AHH', 'B365CAHA', 'AvgC>2.5', 'B365<2.5', 'PC>2.5', 'VCCD', 'WHCH', 'AvgAHH', 'B365C<2.5', 'AvgA'}
SP1_2425.csv: missing={'BbAvH', 'VCA', 'BbMxD', 'VCH', 'BbAHh', 'SJA', 'IWA', 'BbAv<2.5', 'BbAvAHH', 'BbAv>2.5', 'SJH', 'BbMx>2.5', 'BbMxAHH', 'BbAvA', 'BbAH', 'BbMxAHA', 'LBD', 'BbMxA', 'LBH', 'BbOU', 'BbMx<2.5', 'SJD', 'IWD', 'BbAvD', 'BbAvAHA', 'LBA', 'VCD', 'Bb1X2', 'IWH', 'BbMxH'}, extra={'B365AHA', 'AvgH', 'BFECA', 'AHh', 'PAHH', 'AvgCAHH', 'BFD', 'BFED', 'MaxD', 'WHCA', 'Avg>2.5', 'MaxAHH', 'BWCH', 'AvgCH', 'B365CAHH', 'AvgCA', 'AvgCAHA', 'B365AHH', 'WHCH', 'AvgA', 'BFCD', '1XBA', 'BFEAHH', 'B365CA', 'MaxCA', 'BFECAHH', 'PC<2.5', 'AvgC<2.5', 'P>2.5', 'AvgD', 'WHCD', 'Time', '1XBCH', 'MaxA', 'MaxCD', 'BFEC<2.5', 'BFCH', 'B365<2.5', 'BFA', 'PC>2.5', 'B365>2.5', 'PAHA', '1XBH', 'Max>2.5', 'MaxCAHA', 'BFECD', 'MaxCH', 'BFEAHA', 'BFCA', 'PCAHA', 'AvgCD', 'AvgAHA', 'BFECH', 'MaxAHA', 'P<2.5', '1XBCA', 'BFEH', 'MaxC>2.5', 'PCAHH', 'B365CAHA', 'AvgAHH', 'BFE<2.5', 'B365C<2.5', 'MaxH', 'Avg<2.5', '1XBD', 'BFEA', 'AHCh', 'BFEC>2.5', 'BWCA', 'B365C>2.5', 'MaxC<2.5', 'BFE>2.5', '1XBCD', 'MaxCAHH', 'BWCD', 'B365CH', 'BFECAHA', 'Max<2.5', 'B365CD', 'AvgC>2.5', 'BFH'}
SP1_2526.csv: missing={'BbAvH', 'VCA', 'BbMxD', 'VCH', 'BbAHh', 'SJA', 'IWA', 'WHD', 'BbAv<2.5', 'BbAvAHH', 'WHH', 'WHA', 'BbAv>2.5', 'SJH', 'BbMx>2.5', 'BbMxAHH', 'BbAvA', 'BbAH', 'BbMxAHA', 'BbMxA', 'BbMx<2.5', 'BbOU', 'SJD', 'IWD', 'BbAvD', 'BbAvAHA', 'VCD', 'Bb1X2', 'IWH', 'BbMxH'}, extra={'B365AHA', 'AvgH', 'BFECA', 'AHh', 'PAHH', 'AvgCAHH', 'CLCA', 'BFED', 'MaxD', 'Avg>2.5', 'MaxAHH', 'BWCH', 'AvgCH', 'B365CAHH', 'AvgCA', 'BVH', 'AvgCAHA', 'B365AHH', 'BMGMH', 'AvgA', 'BFDA', 'BVCA', 'BFEAHH', 'B365CA', 'BVD', 'LBCA', 'MaxCA', 'CLCD', 'BFECAHH', 'LBCH', 'PC<2.5', 'AvgC<2.5', 'BMGMA', 'P>2.5', 'BVCH', 'AvgD', 'BMGMD', 'Time', 'BFDCH', 'MaxA', 'MaxCD', 'BFEC<2.5', 'B365<2.5', 'PC>2.5', 'CLCH', 'BFDD', 'B365>2.5', 'CLA', 'LBCD', 'PAHA', 'Max>2.5', 'MaxCAHA', 'BFECD', 'MaxCH', 'BFEAHA', 'BFDCA', 'PCAHA', 'AvgCD', 'AvgAHA', 'BFECH', 'MaxAHA', 'P<2.5', 'BMGMCD', 'BFEH', 'MaxC>2.5', 'PCAHH', 'CLH', 'B365CAHA', 'AvgAHH', 'BFE<2.5', 'B365C<2.5', 'BMGMCH', 'CLD', 'MaxH', 'Avg<2.5', 'BFEA', 'AHCh', 'BFEC>2.5', 'BWCA', 'B365C>2.5', 'BFDH', 'MaxC<2.5', 'BVA', 'BFE>2.5', 'MaxCAHH', 'BWCD', 'B365CH', 'BFECAHA', 'Max<2.5', 'BVCD', 'B365CD', 'BFDCD', 'AvgC>2.5', 'BMGMCA'}

Combined shape: (4940, 182)
Date range: 01/02/14 to 31/12/2022

In [14]:
print(df_combined["Date"].dtype)
print(df_combined["Date"].head(10))

str
0    17/08/13
1    17/08/13
2    17/08/13
3    18/08/13
4    18/08/13
5    18/08/13
6    18/08/13
7    19/08/13
8    19/08/13
9    19/08/13
Name: Date, dtype: str

In [15]:
# Check date formats across seasons
for file, df in zip(csv_files, dfs):
    print(f"{file.name}: {df['Date'].iloc[0]}")

SP1_1314.csv: 17/08/13
SP1_1415.csv: 23/08/14
SP1_1516.csv: 21/08/15
SP1_1617.csv: 19/08/16
SP1_1718.csv: 18/08/17
SP1_1819.csv: 17/08/2018
SP1_1920.csv: 16/08/2019
SP1_2021.csv: 12/09/2020
SP1_2122.csv: 13/08/2021
SP1_2223.csv: 12/08/2022
SP1_2324.csv: 11/08/2023
SP1_2425.csv: 15/08/2024
SP1_2526.csv: 15/08/2025

In [16]:
df_combined["Date"] = pd.to_datetime(
    df_combined["Date"], 
    dayfirst=True
)

print(df_combined["Date"].dtype)
print(f"Date range: {df_combined['Date'].min()} to {df_combined['Date'].max()}")

datetime64[us]
Date range: 2013-08-17 00:00:00 to 2026-05-24 00:00:00

C:\Users\aitor\AppData\Local\Temp\ipykernel_23476\437655062.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_combined["Date"] = pd.to_datetime(

In [17]:
# Home advantage analysis
total = len(df_combined)
home_wins = (df_combined["FTR"] == "H").sum()
draws = (df_combined["FTR"] == "D").sum()
away_wins = (df_combined["FTR"] == "A").sum()

print(f"Home wins: {home_wins/total:.1%}")
print(f"Draws:     {draws/total:.1%}")
print(f"Away wins: {away_wins/total:.1%}")

Home wins: 45.8%
Draws:     25.6%
Away wins: 28.6%

In [ ]:
# Calculate implied probabilities from Bet365 odds
df_combined["B365_implied_H"] = 1 / df_combined["B365H"]
df_combined["B365_implied_D"] = 1 / df_combined["B365D"]
df_combined["B365_implied_A"] = 1 / df_combined["B365A"]

# Sum of implied probabilities (should be > 1 due to bookmaker margin)
df_combined["B365_overround"] = (
    df_combined["B365_implied_H"] + 
    df_combined["B365_implied_D"] + 
    df_combined["B365_implied_A"]
)

print(f"Mean overround: {df_combined['B365_overround'].mean():.4f}")
print(f"Min overround:  {df_combined['B365_overround'].min():.4f}")
print(f"Max overround:  {df_combined['B365_overround'].max():.4f}")

In [ ]:
bookmakers = {
    "B365": ("B365H", "B365D", "B365A"),
    "BW": ("BWH", "BWD", "BWA"),
    "IW": ("IWH", "IWD", "IWA"),
    "PS": ("PSH", "PSD", "PSA"),
    "WH": ("WHH", "WHD", "WHA"),
}

for bk, (h_col, d_col, a_col) in bookmakers.items():
    df_combined[f"{bk}_implied_H"] = 1 / df_combined[h_col]
    df_combined[f"{bk}_implied_D"] = 1 / df_combined[d_col]
    df_combined[f"{bk}_implied_A"] = 1 / df_combined[a_col]
    df_combined[f"{bk}_overround"] = (
        df_combined[f"{bk}_implied_H"]
        + df_combined[f"{bk}_implied_D"]
        + df_combined[f"{bk}_implied_A"]
    )

for bk in bookmakers:
    col = f"{bk}_overround"
    print(
        f"{bk} mean: {df_combined[col].mean():.4f}, "
        f"min: {df_combined[col].min():.4f}, "
        f"max: {df_combined[col].max():.4f}"
    )