## 1. Data analysis

In [24]:
import os
print(os.getcwd())

c:\Users\aitor\Desktop\Proyectos\football-ml\notebooks

In [25]:
import pandas as pd
import pathlib

# Get project root (one level up from notebooks/)
PROJECT_ROOT = pathlib.Path().resolve().parent
data_path = PROJECT_ROOT / "data" / "raw" / "laliga" / "SP1_1314.csv"

df = pd.read_csv(data_path)
print(df.shape)
print(df.columns.tolist())

(380, 67)
['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'SJH', 'SJD', 'SJA', 'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA', 'PSCH', 'PSCD', 'PSCA']

In [26]:
# Key columns explanation
key_columns = {
    "Div": "Division (SP1 = La Liga)",
    "Date": "Match date",
    "HomeTeam": "Home team name",
    "AwayTeam": "Away team name",
    "FTHG": "Full Time Home Goals",
    "FTAG": "Full Time Away Goals",
    "FTR": "Full Time Result (H/D/A)",
    "HTHG": "Half Time Home Goals",
    "HTAG": "Half Time Away Goals",
    "HTR": "Half Time Result",
    "HS": "Home Shots",
    "AS": "Away Shots",
    "HST": "Home Shots on Target",
    "AST": "Away Shots on Target",
    "HF": "Home Fouls",
    "AF": "Away Fouls",
    "HC": "Home Corners",
    "AC": "Away Corners",
    "HY": "Home Yellow cards",
    "AY": "Away Yellow cards",
    "HR": "Home Red cards",
    "AR": "Away Red cards",
    "B365H": "Bet365 odds Home win",
    "B365D": "Bet365 odds Draw",
    "B365A": "Bet365 odds Away win",
}

for col, desc in key_columns.items():
    print(f"{col:10} → {desc}")

Div        → Division (SP1 = La Liga)
Date       → Match date
HomeTeam   → Home team name
AwayTeam   → Away team name
FTHG       → Full Time Home Goals
FTAG       → Full Time Away Goals
FTR        → Full Time Result (H/D/A)
HTHG       → Half Time Home Goals
HTAG       → Half Time Away Goals
HTR        → Half Time Result
HS         → Home Shots
AS         → Away Shots
HST        → Home Shots on Target
AST        → Away Shots on Target
HF         → Home Fouls
AF         → Away Fouls
HC         → Home Corners
AC         → Away Corners
HY         → Home Yellow cards
AY         → Away Yellow cards
HR         → Home Red cards
AR         → Away Red cards
B365H      → Bet365 odds Home win
B365D      → Bet365 odds Draw
B365A      → Bet365 odds Away win

In [27]:
df[["Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "FTR", "B365H", "B365D", "B365A"]].head(10)

       Date     HomeTeam    AwayTeam  FTHG  FTAG FTR  B365H  B365D  B365A
0  17/08/13     Sociedad      Getafe     2     0   H   1.73   3.60   4.75
1  17/08/13     Valencia      Malaga     1     0   H   1.53   4.00   6.00
2  17/08/13   Valladolid  Ath Bilbao     1     2   A   2.50   3.30   2.80
3  18/08/13    Barcelona     Levante     7     0   H   1.08  10.00  26.00
4  18/08/13      Osasuna     Granada     1     2   A   2.00   3.30   3.75
5  18/08/13  Real Madrid       Betis     2     1   H   1.17   7.00  17.00
6  18/08/13      Sevilla  Ath Madrid     1     3   A   2.80   3.30   2.50
7  19/08/13      Almeria  Villarreal     2     3   A   2.60   3.20   2.75
8  19/08/13        Celta     Espanol     2     2   D   2.20   3.20   3.40
9  19/08/13    Vallecano       Elche     3     0   H   2.25   3.25   3.25

In [28]:
df[["Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "FTR", "B365H", "B365D", "B365A"]].tail(10)

         Date     HomeTeam    AwayTeam  FTHG  FTAG FTR  B365H  B365D  B365A
370  16/05/14       Malaga     Levante     1     0   H   1.91   3.40   4.00
371  17/05/14    Barcelona  Ath Madrid     1     1   D   1.85   3.80   4.50
372  17/05/14  Real Madrid     Espanol     3     1   H   1.33   5.00   8.50
373  17/05/14     Valencia       Celta     2     1   H   1.75   3.75   4.50
374  18/05/14      Almeria  Ath Bilbao     0     0   D   2.25   3.40   3.10
375  18/05/14      Osasuna       Betis     2     1   H   1.36   5.00   7.50
376  18/05/14      Sevilla       Elche     3     1   H   1.80   3.75   4.20
377  18/05/14     Sociedad  Villarreal     1     2   A   2.00   3.60   3.50
378  18/05/14   Valladolid     Granada     0     1   A   2.10   3.30   3.50
379  18/05/14    Vallecano      Getafe     1     2   A   4.00   3.10   2.05

In [29]:
# Home advantage analysis
total = len(df)
home_wins = (df["FTR"] == "H").sum()
draws = (df["FTR"] == "D").sum()
away_wins = (df["FTR"] == "A").sum()

print(f"Home wins: {home_wins/total:.1%}")
print(f"Draws:     {draws/total:.1%}")
print(f"Away wins: {away_wins/total:.1%}")

Home wins: 47.1%
Draws:     22.6%
Away wins: 30.3%

In [30]:
# Get all CSV files matching the pattern
csv_files = sorted(PROJECT_ROOT.glob("data/raw/laliga/SP1_*.csv"))

# Load all dataframes
dfs = [pd.read_csv(file) for file in csv_files]

# Check if all have the same columns
columns_match = all(df.columns.equals(dfs[0].columns) for df in dfs)
print(f"All dataframes have same columns: {columns_match}")

if not columns_match:
    print("\nColumns per file:")
for file, df in zip(csv_files, dfs):
    missing = set(dfs[0].columns) - set(df.columns)
    extra = set(df.columns) - set(dfs[0].columns)
    if missing or extra:
        print(f"{file.name}: missing={missing}, extra={extra}")

# Concatenate all dataframes
df_combined = pd.concat(dfs, ignore_index=True)
print(f"\nCombined shape: {df_combined.shape}")
print(f"Date range: {df_combined['Date'].min()} to {df_combined['Date'].max()}")

All dataframes have same columns: False

Columns per file:
SP1_1516.csv: missing={'SJD', 'SJH', 'SJA'}, extra=set()
SP1_1617.csv: missing={'SJD', 'SJH', 'SJA'}, extra=set()
SP1_1718.csv: missing={'SJD', 'SJH', 'SJA'}, extra=set()
SP1_1819.csv: missing={'LBH', 'SJD', 'SJA', 'LBA', 'LBD', 'SJH'}, extra=set()
SP1_1920.csv: missing={'BbAvH', 'BbMxD', 'BbAHh', 'SJA', 'BbAv<2.5', 'BbAvAHH', 'BbAv>2.5', 'SJH', 'BbMx>2.5', 'BbMxAHH', 'BbAvA', 'BbAH', 'BbMxAHA', 'LBD', 'BbMxA', 'LBH', 'BbOU', 'BbMx<2.5', 'SJD', 'BbAvD', 'BbAvAHA', 'LBA', 'Bb1X2', 'BbMxH'}, extra={'MaxH', 'B365>2.5', 'VCCA', 'Avg<2.5', 'B365CA', 'B365AHA', 'IWCH', 'AvgH', 'MaxCA', 'PAHA', 'AHCh', 'AHh', 'BWCA', 'B365C>2.5', 'IWCD', 'PAHH', 'MaxC<2.5', 'Max>2.5', 'MaxCAHA', 'AvgCAHH', 'IWCA', 'MaxCH', 'PCAHA', 'PC<2.5', 'AvgC<2.5', 'VCCH', 'AvgCD', 'MaxD', 'WHCA', 'AvgAHA', 'BWCD', 'Avg>2.5', 'MaxCAHH', 'P>2.5', 'MaxAHH', 'BWCH', 'AvgCH', 'MaxAHA', 'B365CAHH', 'AvgD', 'P<2.5', 'B365CH', 'WHCD', 'Time', 'AvgCA', 'MaxC>2.5', 'AvgCAHA', 'Max<2.5', 'PCAHH', 'MaxA', 'MaxCD', 'B365CD', 'B365AHH', 'B365CAHA', 'AvgC>2.5', 'B365<2.5', 'PC>2.5', 'VCCD', 'WHCH', 'AvgAHH', 'B365C<2.5', 'AvgA'}
SP1_2021.csv: missing={'BbAvH', 'BbMxD', 'BbAHh', 'SJA', 'BbAv<2.5', 'BbAvAHH', 'BbAv>2.5', 'SJH', 'BbMx>2.5', 'BbMxAHH', 'BbAvA', 'BbAH', 'BbMxAHA', 'LBD', 'BbMxA', 'LBH', 'BbOU', 'BbMx<2.5', 'SJD', 'BbAvD', 'BbAvAHA', 'LBA', 'Bb1X2', 'BbMxH'}, extra={'MaxH', 'B365>2.5', 'VCCA', 'Avg<2.5', 'B365CA', 'B365AHA', 'IWCH', 'AvgH', 'MaxCA', 'PAHA', 'AHCh', 'AHh', 'BWCA', 'B365C>2.5', 'IWCD', 'PAHH', 'MaxC<2.5', 'Max>2.5', 'MaxCAHA', 'AvgCAHH', 'IWCA', 'MaxCH', 'PCAHA', 'PC<2.5', 'AvgC<2.5', 'VCCH', 'AvgCD', 'MaxD', 'WHCA', 'AvgAHA', 'BWCD', 'Avg>2.5', 'MaxCAHH', 'P>2.5', 'MaxAHH', 'BWCH', 'AvgCH', 'MaxAHA', 'B365CAHH', 'AvgD', 'P<2.5', 'B365CH', 'WHCD', 'Time', 'AvgCA', 'MaxC>2.5', 'AvgCAHA', 'Max<2.5', 'PCAHH', 'MaxA', 'MaxCD', 'B365CD', 'B365AHH', 'B365CAHA', 'AvgC>2.5', 'B365<2.5', 'PC>2.5', 'VCCD', 'WHCH', 'AvgAHH', 'B365C<2.5', 'AvgA'}
SP1_2122.csv: missing={'BbAvH', 'BbMxD', 'BbAHh', 'SJA', 'BbAv<2.5', 'BbAvAHH', 'BbAv>2.5', 'SJH', 'BbMx>2.5', 'BbMxAHH', 'BbAvA', 'BbAH', 'BbMxAHA', 'LBD', 'BbMxA', 'LBH', 'BbOU', 'BbMx<2.5', 'SJD', 'BbAvD', 'BbAvAHA', 'LBA', 'Bb1X2', 'BbMxH'}, extra={'MaxH', 'B365>2.5', 'VCCA', 'Avg<2.5', 'B365CA', 'B365AHA', 'IWCH', 'AvgH', 'MaxCA', 'PAHA', 'AHCh', 'AHh', 'BWCA', 'B365C>2.5', 'IWCD', 'PAHH', 'MaxC<2.5', 'Max>2.5', 'MaxCAHA', 'AvgCAHH', 'IWCA', 'MaxCH', 'PCAHA', 'PC<2.5', 'AvgC<2.5', 'VCCH', 'AvgCD', 'MaxD', 'WHCA', 'AvgAHA', 'BWCD', 'Avg>2.5', 'MaxCAHH', 'P>2.5', 'MaxAHH', 'BWCH', 'AvgCH', 'MaxAHA', 'B365CAHH', 'AvgD', 'P<2.5', 'B365CH', 'WHCD', 'Time', 'AvgCA', 'MaxC>2.5', 'AvgCAHA', 'Max<2.5', 'PCAHH', 'MaxA', 'MaxCD', 'B365CD', 'B365AHH', 'B365CAHA', 'AvgC>2.5', 'B365<2.5', 'PC>2.5', 'VCCD', 'WHCH', 'AvgAHH', 'B365C<2.5', 'AvgA'}
SP1_2223.csv: missing={'BbAvH', 'BbMxD', 'BbAHh', 'SJA', 'BbAv<2.5', 'BbAvAHH', 'BbAv>2.5', 'SJH', 'BbMx>2.5', 'BbMxAHH', 'BbAvA', 'BbAH', 'BbMxAHA', 'LBD', 'BbMxA', 'LBH', 'BbOU', 'BbMx<2.5', 'SJD', 'BbAvD', 'BbAvAHA', 'LBA', 'Bb1X2', 'BbMxH'}, extra={'MaxH', 'B365>2.5', 'VCCA', 'Avg<2.5', 'B365CA', 'B365AHA', 'IWCH', 'AvgH', 'MaxCA', 'PAHA', 'AHCh', 'AHh', 'BWCA', 'B365C>2.5', 'IWCD', 'PAHH', 'MaxC<2.5', 'Max>2.5', 'MaxCAHA', 'AvgCAHH', 'IWCA', 'MaxCH', 'PCAHA', 'PC<2.5', 'AvgC<2.5', 'VCCH', 'AvgCD', 'MaxD', 'WHCA', 'AvgAHA', 'BWCD', 'Avg>2.5', 'MaxCAHH', 'P>2.5', 'MaxAHH', 'BWCH', 'AvgCH', 'MaxAHA', 'B365CAHH', 'AvgD', 'P<2.5', 'B365CH', 'WHCD', 'Time', 'AvgCA', 'MaxC>2.5', 'AvgCAHA', 'Max<2.5', 'PCAHH', 'MaxA', 'MaxCD', 'B365CD', 'B365AHH', 'B365CAHA', 'AvgC>2.5', 'B365<2.5', 'PC>2.5', 'VCCD', 'WHCH', 'AvgAHH', 'B365C<2.5', 'AvgA'}
SP1_2324.csv: missing={'BbAvH', 'BbMxD', 'BbAHh', 'SJA', 'BbAv<2.5', 'BbAvAHH', 'BbAv>2.5', 'SJH', 'BbMx>2.5', 'BbMxAHH', 'BbAvA', 'BbAH', 'BbMxAHA', 'LBD', 'BbMxA', 'LBH', 'BbOU', 'BbMx<2.5', 'SJD', 'BbAvD', 'BbAvAHA', 'LBA', 'Bb1X2', 'BbMxH'}, extra={'MaxH', 'B365>2.5', 'VCCA', 'Avg<2.5', 'B365CA', 'B365AHA', 'IWCH', 'AvgH', 'MaxCA', 'PAHA', 'AHCh', 'AHh', 'BWCA', 'B365C>2.5', 'IWCD', 'PAHH', 'MaxC<2.5', 'Max>2.5', 'MaxCAHA', 'AvgCAHH', 'IWCA', 'MaxCH', 'PCAHA', 'PC<2.5', 'AvgC<2.5', 'VCCH', 'AvgCD', 'MaxD', 'WHCA', 'AvgAHA', 'BWCD', 'Avg>2.5', 'MaxCAHH', 'P>2.5', 'MaxAHH', 'BWCH', 'AvgCH', 'MaxAHA', 'B365CAHH', 'AvgD', 'P<2.5', 'B365CH', 'WHCD', 'Time', 'AvgCA', 'MaxC>2.5', 'AvgCAHA', 'Max<2.5', 'PCAHH', 'MaxA', 'MaxCD', 'B365CD', 'B365AHH', 'B365CAHA', 'AvgC>2.5', 'B365<2.5', 'PC>2.5', 'VCCD', 'WHCH', 'AvgAHH', 'B365C<2.5', 'AvgA'}
SP1_2425.csv: missing={'BbAvH', 'VCA', 'BbMxD', 'VCH', 'BbAHh', 'SJA', 'IWA', 'BbAv<2.5', 'BbAvAHH', 'BbAv>2.5', 'SJH', 'BbMx>2.5', 'BbMxAHH', 'BbAvA', 'BbAH', 'BbMxAHA', 'LBD', 'BbMxA', 'LBH', 'BbOU', 'BbMx<2.5', 'SJD', 'IWD', 'BbAvD', 'BbAvAHA', 'LBA', 'VCD', 'Bb1X2', 'IWH', 'BbMxH'}, extra={'B365AHA', 'AvgH', 'BFECA', 'AHh', 'PAHH', 'AvgCAHH', 'BFD', 'BFED', 'MaxD', 'WHCA', 'Avg>2.5', 'MaxAHH', 'BWCH', 'AvgCH', 'B365CAHH', 'AvgCA', 'AvgCAHA', 'B365AHH', 'WHCH', 'AvgA', 'BFCD', '1XBA', 'BFEAHH', 'B365CA', 'MaxCA', 'BFECAHH', 'PC<2.5', 'AvgC<2.5', 'P>2.5', 'AvgD', 'WHCD', 'Time', '1XBCH', 'MaxA', 'MaxCD', 'BFEC<2.5', 'BFCH', 'B365<2.5', 'BFA', 'PC>2.5', 'B365>2.5', 'PAHA', '1XBH', 'Max>2.5', 'MaxCAHA', 'BFECD', 'MaxCH', 'BFEAHA', 'BFCA', 'PCAHA', 'AvgCD', 'AvgAHA', 'BFECH', 'MaxAHA', 'P<2.5', '1XBCA', 'BFEH', 'MaxC>2.5', 'PCAHH', 'B365CAHA', 'AvgAHH', 'BFE<2.5', 'B365C<2.5', 'MaxH', 'Avg<2.5', '1XBD', 'BFEA', 'AHCh', 'BFEC>2.5', 'BWCA', 'B365C>2.5', 'MaxC<2.5', 'BFE>2.5', '1XBCD', 'MaxCAHH', 'BWCD', 'B365CH', 'BFECAHA', 'Max<2.5', 'B365CD', 'AvgC>2.5', 'BFH'}
SP1_2526.csv: missing={'BbAvH', 'VCA', 'BbMxD', 'VCH', 'BbAHh', 'SJA', 'IWA', 'WHD', 'BbAv<2.5', 'BbAvAHH', 'WHH', 'WHA', 'BbAv>2.5', 'SJH', 'BbMx>2.5', 'BbMxAHH', 'BbAvA', 'BbAH', 'BbMxAHA', 'BbMxA', 'BbMx<2.5', 'BbOU', 'SJD', 'IWD', 'BbAvD', 'BbAvAHA', 'VCD', 'Bb1X2', 'IWH', 'BbMxH'}, extra={'B365AHA', 'AvgH', 'BFECA', 'AHh', 'PAHH', 'AvgCAHH', 'CLCA', 'BFED', 'MaxD', 'Avg>2.5', 'MaxAHH', 'BWCH', 'AvgCH', 'B365CAHH', 'AvgCA', 'BVH', 'AvgCAHA', 'B365AHH', 'BMGMH', 'AvgA', 'BFDA', 'BVCA', 'BFEAHH', 'B365CA', 'BVD', 'LBCA', 'MaxCA', 'CLCD', 'BFECAHH', 'LBCH', 'PC<2.5', 'AvgC<2.5', 'BMGMA', 'P>2.5', 'BVCH', 'AvgD', 'BMGMD', 'Time', 'BFDCH', 'MaxA', 'MaxCD', 'BFEC<2.5', 'B365<2.5', 'PC>2.5', 'CLCH', 'BFDD', 'B365>2.5', 'CLA', 'LBCD', 'PAHA', 'Max>2.5', 'MaxCAHA', 'BFECD', 'MaxCH', 'BFEAHA', 'BFDCA', 'PCAHA', 'AvgCD', 'AvgAHA', 'BFECH', 'MaxAHA', 'P<2.5', 'BMGMCD', 'BFEH', 'MaxC>2.5', 'PCAHH', 'CLH', 'B365CAHA', 'AvgAHH', 'BFE<2.5', 'B365C<2.5', 'BMGMCH', 'CLD', 'MaxH', 'Avg<2.5', 'BFEA', 'AHCh', 'BFEC>2.5', 'BWCA', 'B365C>2.5', 'BFDH', 'MaxC<2.5', 'BVA', 'BFE>2.5', 'MaxCAHH', 'BWCD', 'B365CH', 'BFECAHA', 'Max<2.5', 'BVCD', 'B365CD', 'BFDCD', 'AvgC>2.5', 'BMGMCA'}

Combined shape: (4940, 182)
Date range: 01/02/14 to 31/12/2022

In [31]:
print(df_combined["Date"].dtype)
print(df_combined["Date"].head(10))

str
0    17/08/13
1    17/08/13
2    17/08/13
3    18/08/13
4    18/08/13
5    18/08/13
6    18/08/13
7    19/08/13
8    19/08/13
9    19/08/13
Name: Date, dtype: str

In [32]:
# Check date formats across seasons
for file, df in zip(csv_files, dfs):
    print(f"{file.name}: {df['Date'].iloc[0]}")

SP1_1314.csv: 17/08/13
SP1_1415.csv: 23/08/14
SP1_1516.csv: 21/08/15
SP1_1617.csv: 19/08/16
SP1_1718.csv: 18/08/17
SP1_1819.csv: 17/08/2018
SP1_1920.csv: 16/08/2019
SP1_2021.csv: 12/09/2020
SP1_2122.csv: 13/08/2021
SP1_2223.csv: 12/08/2022
SP1_2324.csv: 11/08/2023
SP1_2425.csv: 15/08/2024
SP1_2526.csv: 15/08/2025

In [33]:
df_combined["Date"] = pd.to_datetime(
    df_combined["Date"], 
    dayfirst=True
)

print(df_combined["Date"].dtype)
print(f"Date range: {df_combined['Date'].min()} to {df_combined['Date'].max()}")

datetime64[us]
Date range: 2013-08-17 00:00:00 to 2026-05-24 00:00:00

C:\Users\aitor\AppData\Local\Temp\ipykernel_23476\437655062.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_combined["Date"] = pd.to_datetime(

In [34]:
# Home advantage analysis
total = len(df_combined)
home_wins = (df_combined["FTR"] == "H").sum()
draws = (df_combined["FTR"] == "D").sum()
away_wins = (df_combined["FTR"] == "A").sum()

print(f"Home wins: {home_wins/total:.1%}")
print(f"Draws:     {draws/total:.1%}")
print(f"Away wins: {away_wins/total:.1%}")

Home wins: 45.8%
Draws:     25.6%
Away wins: 28.6%

In [35]:
# Calculate implied probabilities from Bet365 odds
df_combined["B365_implied_H"] = 1 / df_combined["B365H"]
df_combined["B365_implied_D"] = 1 / df_combined["B365D"]
df_combined["B365_implied_A"] = 1 / df_combined["B365A"]

# Sum of implied probabilities (should be > 1 due to bookmaker margin)
df_combined["B365_overround"] = (
    df_combined["B365_implied_H"] + 
    df_combined["B365_implied_D"] + 
    df_combined["B365_implied_A"]
)

print(f"Mean overround: {df_combined['B365_overround'].mean():.4f}")
print(f"Min overround:  {df_combined['B365_overround'].min():.4f}")
print(f"Max overround:  {df_combined['B365_overround'].max():.4f}")

Mean overround: 1.0548
Min overround:  1.0167
Max overround:  1.1226

C:\Users\aitor\AppData\Local\Temp\ipykernel_23476\1511198802.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_combined["B365_implied_H"] = 1 / df_combined["B365H"]
C:\Users\aitor\AppData\Local\Temp\ipykernel_23476\1511198802.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_combined["B365_implied_D"] = 1 / df_combined["B365D"]
C:\Users\aitor\AppData\Local\Temp\ipykernel_23476\1511198802.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_combined["B365_implied_A"] = 1 / df_combined["B365A"]
C:\Users\aitor\AppData\Local\Temp\ipykernel_23476\1511198802.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_combined["B365_overround"] = (

In [36]:
bookmakers = {
    "B365": ("B365H", "B365D", "B365A"),
    "BW": ("BWH", "BWD", "BWA"),
    "IW": ("IWH", "IWD", "IWA"),
    "PS": ("PSH", "PSD", "PSA"),
    "WH": ("WHH", "WHD", "WHA"),
}

for bk, (h_col, d_col, a_col) in bookmakers.items():
    df_combined[f"{bk}_implied_H"] = 1 / df_combined[h_col]
    df_combined[f"{bk}_implied_D"] = 1 / df_combined[d_col]
    df_combined[f"{bk}_implied_A"] = 1 / df_combined[a_col]
    df_combined[f"{bk}_overround"] = (
        df_combined[f"{bk}_implied_H"]
        + df_combined[f"{bk}_implied_D"]
        + df_combined[f"{bk}_implied_A"]
    )

for bk in bookmakers:
    col = f"{bk}_overround"
    print(
        f"{bk} mean: {df_combined[col].mean():.4f}, "
        f"min: {df_combined[col].min():.4f}, "
        f"max: {df_combined[col].max():.4f}"
    )

B365 mean: 1.0548, min: 1.0167, max: 1.1226
BW mean: 1.0569, min: 1.0226, max: 1.1296
IW mean: 1.0613, min: 1.0359, max: 1.0937
PS mean: 1.0262, min: 1.0154, max: 1.0704
WH mean: 1.0590, min: 1.0323, max: 1.1803

C:\Users\aitor\AppData\Local\Temp\ipykernel_23476\3339837133.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_combined[f"{bk}_implied_H"] = 1 / df_combined[h_col]
C:\Users\aitor\AppData\Local\Temp\ipykernel_23476\3339837133.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_combined[f"{bk}_implied_D"] = 1 / df_combined[d_col]
C:\Users\aitor\AppData\Local\Temp\ipykernel_23476\3339837133.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_combined[f"{bk}_implied_A"] = 1 / df_combined[a_col]
C:\Users\aitor\AppData\Local\Temp\ipykernel_23476\3339837133.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_combined[f"{bk}_overround"] = (

In [37]:
# Defragment first
df_combined = df_combined.copy()

# Build all new columns at once
new_cols = {}
for bk in bookmakers:
    new_cols[f"{bk}_norm_H"] = df_combined[f"{bk}_implied_H"] / df_combined[f"{bk}_overround"]
    new_cols[f"{bk}_norm_D"] = df_combined[f"{bk}_implied_D"] / df_combined[f"{bk}_overround"]
    new_cols[f"{bk}_norm_A"] = df_combined[f"{bk}_implied_A"] / df_combined[f"{bk}_overround"]

# Add all columns at once
df_combined = pd.concat([df_combined, pd.DataFrame(new_cols, index=df_combined.index)], axis=1)

In [38]:
for bk in bookmakers:
    mean_sum = float((df_combined[f"{bk}_norm_H"] + 
                df_combined[f"{bk}_norm_D"] + 
                df_combined[f"{bk}_norm_A"]).mean(skipna=True))
    print(f"{bk}: sum of normalized probs = {mean_sum:.6f}")

B365: sum of normalized probs = 1.000000
BW: sum of normalized probs = 1.000000
IW: sum of normalized probs = 1.000000
PS: sum of normalized probs = 1.000000
WH: sum of normalized probs = 1.000000

In [39]:
for bk, (h_col, d_col, a_col) in bookmakers.items():
    nulls = df_combined[[h_col, d_col, a_col]].isnull().any(axis=1).sum()
    print(f"{bk}: {nulls} partidos con cuotas missing ({nulls/len(df_combined):.1%})")

B365: 0 partidos con cuotas missing (0.0%)
BW: 161 partidos con cuotas missing (3.3%)
IW: 956 partidos con cuotas missing (19.4%)
PS: 197 partidos con cuotas missing (4.0%)
WH: 481 partidos con cuotas missing (9.7%)

In [40]:
# Find all bookmaker columns that have H, D, A variants
import re

all_cols = df_combined.columns.tolist()

# Find all columns ending in H, D, A that look like odds
bookmaker_h_cols = [c for c in all_cols if c.endswith('H') and not c.startswith('Bb') 
                    and c not in ['FTHG', 'HTAG', 'HST', 'HC', 'HF', 'HY', 'HR', 'HS', 'HTHG']]

# For each H column, check if D and A variants exist
all_bookmakers = {}
for h_col in bookmaker_h_cols:
    prefix = h_col[:-1]
    d_col = f"{prefix}D"
    a_col = f"{prefix}A"
    if d_col in all_cols and a_col in all_cols:
        total = len(df_combined)
        missing = df_combined[[h_col, d_col, a_col]].isnull().any(axis=1).sum()
        coverage = (total - missing) / total
        all_bookmakers[prefix] = coverage

# Sort by coverage
sorted_bks = sorted(all_bookmakers.items(), key=lambda x: x[1], reverse=True)
for bk, coverage in sorted_bks:
    print(f"{bk:15} {coverage:.1%} coverage ({int(coverage*4940)} partidos)")

B365            100.0% coverage (4940 partidos)
B365_implied_   100.0% coverage (4940 partidos)
B365_norm_      100.0% coverage (4940 partidos)
BW              96.7% coverage (4779 partidos)
BW_implied_     96.7% coverage (4779 partidos)
BW_norm_        96.7% coverage (4779 partidos)
PSC             96.1% coverage (4747 partidos)
PS              96.0% coverage (4743 partidos)
PS_implied_     96.0% coverage (4743 partidos)
PS_norm_        96.0% coverage (4743 partidos)
WH              90.3% coverage (4459 partidos)
WH_implied_     90.3% coverage (4459 partidos)
WH_norm_        90.3% coverage (4459 partidos)
VC              84.6% coverage (4180 partidos)
IW              80.6% coverage (3984 partidos)
IW_implied_     80.6% coverage (3984 partidos)
IW_norm_        80.6% coverage (3984 partidos)
Max             53.8% coverage (2660 partidos)
Avg             53.8% coverage (2660 partidos)
B365C           53.8% coverage (2660 partidos)
MaxC            53.8% coverage (2660 partidos)
AvgC            53.8% coverage (2660 partidos)
BWC             50.6% coverage (2500 partidos)
LB              44.3% coverage (2188 partidos)
WHC             44.1% coverage (2178 partidos)
VCC             38.5% coverage (1900 partidos)
IWC             34.5% coverage (1704 partidos)
BFE             14.8% coverage (730 partidos)
BFEC            14.8% coverage (729 partidos)
SJ              8.3% coverage (409 partidos)
BF              7.7% coverage (380 partidos)
BFC             7.7% coverage (380 partidos)
1XBC            7.7% coverage (380 partidos)
BFD             7.7% coverage (378 partidos)
BMGMC           7.7% coverage (378 partidos)
BMGM            7.7% coverage (378 partidos)
BV              7.7% coverage (378 partidos)
BFDC            7.6% coverage (373 partidos)
BVC             7.5% coverage (372 partidos)
1XB             7.5% coverage (370 partidos)
LBC             6.0% coverage (297 partidos)
CL              5.7% coverage (282 partidos)
CLC             5.6% coverage (278 partidos)

In [41]:
# Convert FTR to one-hot encoding
df_combined["real_H"] = (df_combined["FTR"] == "H").astype(int)
df_combined["real_D"] = (df_combined["FTR"] == "D").astype(int)
df_combined["real_A"] = (df_combined["FTR"] == "A").astype(int)

# Verify
print(df_combined[["FTR", "real_H", "real_D", "real_A"]].head(10))

  FTR  real_H  real_D  real_A
0   H       1       0       0
1   H       1       0       0
2   A       0       0       1
3   H       1       0       0
4   A       0       0       1
5   H       1       0       0
6   A       0       0       1
7   A       0       0       1
8   D       0       1       0
9   H       1       0       0

In [42]:
from sklearn.metrics import log_loss, brier_score_loss
import numpy as np

y_true = df_combined[["real_H", "real_D", "real_A"]].values
bookmakers_final = ["B365", "BW", "PS", "WH"]

print(f"{'Casa':10} {'Log Loss':>10} {'Brier Score':>12} {'Accuracy':>10}")
print("-" * 45)

for bk in bookmakers_final:
    mask = df_combined[[f"{bk}_norm_H", f"{bk}_norm_D", f"{bk}_norm_A"]].notna().all(axis=1)
    y_true_bk = y_true[mask]
    y_pred = df_combined.loc[mask, [f"{bk}_norm_H", f"{bk}_norm_D", f"{bk}_norm_A"]].values
    
    ll = log_loss(y_true_bk, y_pred)
    bs = np.mean([brier_score_loss(y_true_bk[:, i], y_pred[:, i]) for i in range(3)])
    
    predicted_result = np.argmax(y_pred, axis=1)
    actual_result = np.argmax(y_true_bk, axis=1)
    acc = (predicted_result == actual_result).mean()
    
    print(f"{bk:10} {ll:>10.4f} {bs:>12.4f} {acc:>10.1%}")

Casa         Log Loss  Brier Score   Accuracy
---------------------------------------------
B365           0.9587       0.1896      54.1%
BW             0.9606       0.1900      54.0%
PS             0.9576       0.1894      54.2%
WH             0.9596       0.1898      54.0%

In [43]:
# Check coverage of closing odds
closing_cols = {
    "B365": ("B365H", "B365D", "B365A", "B365CH", "B365CD", "B365CA"),
    "PS":   ("PSH", "PSD", "PSA", "PSCH", "PSCD", "PSCA"),
    "BW":   ("BWH", "BWD", "BWA", "BWCH", "BWCD", "BWCA"),
    "WH":   ("WHH", "WHD", "WHA", "WHCH", "WHCD", "WHCA"),
}

for bk, cols in closing_cols.items():
    available = [c for c in cols if c in df_combined.columns]
    missing_cols = [c for c in cols if c not in df_combined.columns]
    if missing_cols:
        print(f"{bk}: faltan columnas {missing_cols}")
    else:
        both = df_combined[list(cols)].notna().all(axis=1).sum()
        print(f"{bk}: {both} partidos con apertura Y cierre ({both/len(df_combined):.1%})")

B365: 2660 partidos con apertura Y cierre (53.8%)
PS: 4741 partidos con apertura Y cierre (96.0%)
BW: 2498 partidos con apertura Y cierre (50.6%)
WH: 2178 partidos con apertura Y cierre (44.1%)

In [44]:
# Analyze odds movement for Pinnacle
ps_both = df_combined[df_combined[["PSH", "PSD", "PSA", "PSCH", "PSCD", "PSCA"]].notna().all(axis=1)].copy()

# Calculate implied probs for opening and closing
for result, open_col, close_col in [("H", "PSH", "PSCH"), ("D", "PSD", "PSCD"), ("A", "PSA", "PSCA")]:
    ps_both[f"open_prob_{result}"] = 1 / ps_both[open_col]
    ps_both[f"close_prob_{result}"] = 1 / ps_both[close_col]
    ps_both[f"movement_{result}"] = ps_both[f"close_prob_{result}"] - ps_both[f"open_prob_{result}"]

# Average movement per result
print("Media de movimiento de probabilidad (cierre - apertura):")
print(f"  Local:    {ps_both['movement_H'].mean():+.4f}")
print(f"  Empate:   {ps_both['movement_D'].mean():+.4f}")
print(f"  Visitante:{ps_both['movement_A'].mean():+.4f}")

# How often does the market move significantly (>2%)
threshold = 0.02
for result in ["H", "D", "A"]:
    big_move = (ps_both[f"movement_{result}"].abs() > threshold).mean()
    print(f"\nMovimiento >2% en {result}: {big_move:.1%} de partidos")

Media de movimiento de probabilidad (cierre - apertura):
  Local:    +0.0000
  Empate:   +0.0013
  Visitante:-0.0028

Movimiento >2% en H: 45.4% de partidos

Movimiento >2% en D: 13.8% de partidos

Movimiento >2% en A: 38.3% de partidos

In [45]:
from sklearn.metrics import log_loss
import numpy as np

# Normalize opening odds
ps_both["open_sum"] = ps_both["open_prob_H"] + ps_both["open_prob_D"] + ps_both["open_prob_A"]
ps_both["open_norm_H"] = ps_both["open_prob_H"] / ps_both["open_sum"]
ps_both["open_norm_D"] = ps_both["open_prob_D"] / ps_both["open_sum"]
ps_both["open_norm_A"] = ps_both["open_prob_A"] / ps_both["open_sum"]

# Normalize closing odds
ps_both["close_sum"] = ps_both["close_prob_H"] + ps_both["close_prob_D"] + ps_both["close_prob_A"]
ps_both["close_norm_H"] = ps_both["close_prob_H"] / ps_both["close_sum"]
ps_both["close_norm_D"] = ps_both["close_prob_D"] / ps_both["close_sum"]
ps_both["close_norm_A"] = ps_both["close_prob_A"] / ps_both["close_sum"]

# Results
y_true = ps_both[["real_H", "real_D", "real_A"]].values
y_open = ps_both[["open_norm_H", "open_norm_D", "open_norm_A"]].values
y_close = ps_both[["close_norm_H", "close_norm_D", "close_norm_A"]].values

ll_open = log_loss(y_true, y_open)
ll_close = log_loss(y_true, y_close)

acc_open = (np.argmax(y_open, axis=1) == np.argmax(y_true, axis=1)).mean()
acc_close = (np.argmax(y_close, axis=1) == np.argmax(y_true, axis=1)).mean()

print(f"{'':15} {'Log Loss':>10} {'Accuracy':>10}")
print(f"{'PS Apertura':15} {ll_open:>10.4f} {acc_open:>10.1%}")
print(f"{'PS Cierre':15} {ll_close:>10.4f} {acc_close:>10.1%}")
print(f"\nMejora Log Loss: {ll_open - ll_close:+.4f}")

                  Log Loss   Accuracy
PS Apertura         0.9576      54.2%
PS Cierre           0.9543      54.6%

Mejora Log Loss: +0.0033

In [ ]:
bookmakers_oc = {
    "B365": {"open": ("B365H", "B365D", "B365A"), "close": ("B365CH", "B365CD", "B365CA")},
    "BW":   {"open": ("BWH", "BWD", "BWA"),       "close": ("BWCH", "BWCD", "BWCA")},
    "PS":   {"open": ("PSH", "PSD", "PSA"),        "close": ("PSCH", "PSCD", "PSCA")},
    "WH":   {"open": ("WHH", "WHD", "WHA"),        "close": ("WHCH", "WHCD", "WHCA")},
}

for bk, cols in bookmakers_oc.items():
    open_cols = cols["open"]   
    close_cols = cols["close"]

    # Analyze odds movement for all bookmakers with both open and close bets
    all_cols = list(open_cols) + list(close_cols)
    bk_both = df_combined[df_combined[all_cols].notna().all(axis=1)].copy()

    # Calculate implied probs for opening and closing
    for result, open_col, close_col in zip(["H", "D", "A"], open_cols, close_cols): #Empareja los datos de varias listas en paralelo
        bk_both[f"open_prob_{result}"] = 1 / bk_both[open_col]
        bk_both[f"close_prob_{result}"] = 1 / bk_both[close_col]
        bk_both[f"movement_{result}"] = bk_both[f"close_prob_{result}"] - bk_both[f"open_prob_{result}"]

    # Average movement per result
    print("\nMedia de movimiento de probabilidad (cierre - apertura):")
    print(f"--- {bk} ({len(bk_both)} partidos) ---")
    print(f"  Local:    {bk_both['movement_H'].mean():+.4f}")
    print(f"  Empate:   {bk_both['movement_D'].mean():+.4f}")
    print(f"  Visitante:{bk_both['movement_A'].mean():+.4f}")

    # How often does the market move significantly (>2%)
    threshold = 0.02
    print(f"\nMovimiento >2% en {bk} ({len(bk_both)} partidos):")
    for result in ["H", "D", "A"]:
        big_move = (bk_both[f"movement_{result}"].abs() > threshold).mean()
        print(f"Movimiento >2% en {result}: {big_move:.1%} de partidos")

    # How often does the market move significantly (>2%)
    threshold = 0.10
    print(f"\nMovimiento >10% en {bk} ({len(bk_both)} partidos):")
    for result in ["H", "D", "A"]:
        big_move = (bk_both[f"movement_{result}"].abs() > threshold).mean()
        print(f"Movimiento >10% en {result}: {big_move:.1%} de partidos")

Media de movimiento de probabilidad (cierre - apertura):
--- B365 (2660 partidos) ---
  Local:    +0.0017
  Empate:   +0.0006
  Visitante:-0.0017

Movimiento >2% en B365 (2660 partidos):
Movimiento >2% en H: 49.1% de partidos
Movimiento >2% en D: 16.5% de partidos
Movimiento >2% en A: 44.1% de partidos

Movimiento >10% en B365 (2660 partidos):
Movimiento >10% en H: 0.6% de partidos
Movimiento >10% en D: 0.0% de partidos
Movimiento >10% en A: 0.6% de partidos

Media de movimiento de probabilidad (cierre - apertura):
--- BW (2498 partidos) ---
  Local:    +0.0006
  Empate:   +0.0028
  Visitante:-0.0036

Movimiento >2% en BW (2498 partidos):
Movimiento >2% en H: 45.4% de partidos
Movimiento >2% en D: 16.5% de partidos
Movimiento >2% en A: 40.3% de partidos

Movimiento >10% en BW (2498 partidos):
Movimiento >10% en H: 0.6% de partidos
Movimiento >10% en D: 0.0% de partidos
Movimiento >10% en A: 0.4% de partidos

Media de movimiento de probabilidad (cierre - apertura):
--- PS (4741 partidos) ---
  Local:    +0.0000
  Empate:   +0.0013
  Visitante:-0.0028

Movimiento >2% en PS (4741 partidos):
Movimiento >2% en H: 45.4% de partidos
Movimiento >2% en D: 13.8% de partidos
Movimiento >2% en A: 38.3% de partidos

Movimiento >10% en PS (4741 partidos):
Movimiento >10% en H: 0.5% de partidos
Movimiento >10% en D: 0.0% de partidos
Movimiento >10% en A: 0.5% de partidos

Media de movimiento de probabilidad (cierre - apertura):
--- WH (2178 partidos) ---
  Local:    +0.0009
  Empate:   +0.0016
  Visitante:-0.0024

Movimiento >2% en WH (2178 partidos):
Movimiento >2% en H: 47.2% de partidos
Movimiento >2% en D: 14.6% de partidos
Movimiento >2% en A: 41.4% de partidos

Movimiento >10% en WH (2178 partidos):
Movimiento >10% en H: 0.6% de partidos
Movimiento >10% en D: 0.0% de partidos
Movimiento >10% en A: 0.6% de partidos

In [54]:
from sklearn.metrics import log_loss, brier_score_loss
import numpy as np

for bk, cols in bookmakers_oc.items():
    # 1. Extraer columnas
    open_cols = cols["open"]   
    close_cols = cols["close"]

    # 2. Filtrar partidos con datos completos
    all_cols = list(open_cols) + list(close_cols)
    bk_both = df_combined[df_combined[all_cols].notna().all(axis=1)].copy()

    # 3. Calcular probabilidades implícitas
    for result, open_col, close_col in zip(["H", "D", "A"], open_cols, close_cols):
        bk_both[f"open_prob_{result}"] = 1 / bk_both[open_col]
        bk_both[f"close_prob_{result}"] = 1 / bk_both[close_col]

    # 4. Normalizar ← rellena tú
    bk_both["open_sum"] = bk_both["open_prob_H"] + bk_both["open_prob_D"] + bk_both["open_prob_A"]
    bk_both["open_norm_H"] = bk_both["open_prob_H"] / bk_both["open_sum"]
    bk_both["open_norm_D"] = bk_both["open_prob_D"] / bk_both["open_sum"]
    bk_both["open_norm_A"] = bk_both["open_prob_A"] / bk_both["open_sum"]
    bk_both["close_sum"] = bk_both["close_prob_H"] + bk_both["close_prob_D"] + bk_both["close_prob_A"]
    bk_both["close_norm_H"] = bk_both["close_prob_H"] / bk_both["close_sum"]
    bk_both["close_norm_D"] = bk_both["close_prob_D"] / bk_both["close_sum"]
    bk_both["close_norm_A"] = bk_both["close_prob_A"] / bk_both["close_sum"]

    # 5. Calcular métricas ← rellena tú
    y_true = bk_both[["real_H", "real_D", "real_A"]].values
    y_open = bk_both[["open_norm_H", "open_norm_D", "open_norm_A"]].values
    y_close = bk_both[["close_norm_H", "close_norm_D", "close_norm_A"]].values

    ll_open = log_loss(y_true, y_open)
    ll_close = log_loss(y_true, y_close)
    bs_open = np.mean([brier_score_loss(y_true[:, i], y_open[:, i]) for i in range(3)])
    bs_close = np.mean([brier_score_loss(y_true[:, i], y_close[:, i]) for i in range(3)])
    acc_open = (np.argmax(y_open, axis=1) == np.argmax(y_true, axis=1)).mean()
    acc_close = (np.argmax(y_close, axis=1) == np.argmax(y_true, axis=1)).mean()

    # 6. Imprimir
    print(f"\n--- {bk} ({len(bk_both)} partidos) ---")
    print(f"{'':15} {'Log Loss':>10} {'Brier':>8} {'Accuracy':>10}")
    print(f"{'Apertura':15} {ll_open:>10.4f} {bs_open:>8.4f} {acc_open:>10.1%}")
    print(f"{'Cierre':15} {ll_close:>10.4f} {bs_close:>8.4f} {acc_close:>10.1%}")
    print(f"Mejora LL: {ll_open - ll_close:+.4f}  Mejora BS: {bs_open - bs_close:+.4f}")

--- B365 (2660 partidos) ---
                  Log Loss    Brier   Accuracy
Apertura            0.9720   0.1926      53.8%
Cierre              0.9702   0.1922      53.8%
Mejora LL: +0.0018  Mejora BS: +0.0004

--- BW (2498 partidos) ---
                  Log Loss    Brier   Accuracy
Apertura            0.9760   0.1935      53.4%
Cierre              0.9729   0.1928      53.8%
Mejora LL: +0.0031  Mejora BS: +0.0007

--- PS (4741 partidos) ---
                  Log Loss    Brier   Accuracy
Apertura            0.9576   0.1894      54.2%
Cierre              0.9543   0.1887      54.6%
Mejora LL: +0.0033  Mejora BS: +0.0007

--- WH (2178 partidos) ---
                  Log Loss    Brier   Accuracy
Apertura            0.9767   0.1938      53.4%
Cierre              0.9737   0.1931      53.6%
Mejora LL: +0.0031  Mejora BS: +0.0007

## 2. Goals Analysis

In [56]:
df_combined["TotalGoals"] = df_combined["FTHG"] + df_combined["FTAG"]
print(df_combined[["FTHG", "FTAG", "TotalGoals"]].head(10))

total_goals_mean = df_combined["TotalGoals"].mean()
print(f"Media de goles por partido: {total_goals_mean:.2f}")
home_goals_mean = df_combined["FTHG"].mean()
print(f"Media de goles locales por partido: {home_goals_mean:.2f}")
away_goals_mean = df_combined["FTAG"].mean()
print(f"Media de goles visitantes por partido: {away_goals_mean:.2f}")

   FTHG  FTAG  TotalGoals
0     2     0           2
1     1     0           1
2     1     2           3
3     7     0           7
4     1     2           3
5     2     1           3
6     1     3           4
7     2     3           5
8     2     2           4
9     3     0           3
Media de goles por partido: 2.64
Media de goles locales por partido: 1.51
Media de goles visitantes por partido: 1.13

In [60]:
import numpy as np

year = df_combined["Date"].dt.year
month = df_combined["Date"].dt.month

season_start = np.where(month >= 8, year, year - 1)
season_end = (season_start + 1) % 100

df_combined["Season"] = (
    pd.Series(season_start).astype(str) 
    + "/" 
    + pd.Series(season_end).astype(str).str.zfill(2)
)

print(df_combined[["Date", "Season"]].head(10))
print(df_combined[["Date", "Season"]].tail(10))

        Date   Season
0 2013-08-17  2013/14
1 2013-08-17  2013/14
2 2013-08-17  2013/14
3 2013-08-18  2013/14
4 2013-08-18  2013/14
5 2013-08-18  2013/14
6 2013-08-18  2013/14
7 2013-08-19  2013/14
8 2013-08-19  2013/14
9 2013-08-19  2013/14
           Date   Season
4930 2026-05-23  2025/26
4931 2026-05-23  2025/26
4932 2026-05-23  2025/26
4933 2026-05-23  2025/26
4934 2026-05-23  2025/26
4935 2026-05-23  2025/26
4936 2026-05-23  2025/26
4937 2026-05-23  2025/26
4938 2026-05-23  2025/26
4939 2026-05-24  2025/26

In [61]:
df_combined.groupby("Season")[["TotalGoals", "FTHG", "FTAG"]].mean()

         TotalGoals      FTHG      FTAG
Season
2013/14    2.750000  1.631579  1.118421
2014/15    2.655263  1.536842  1.118421
2015/16    2.744737  1.618421  1.126316
2016/17    2.942105  1.663158  1.278947
2017/18    2.694737  1.547368  1.147368
2018/19    2.586842  1.452632  1.134211
2019/20    2.478947  1.436842  1.042105
2020/21    2.507895  1.368421  1.139474
2021/22    2.502632  1.421053  1.081579
2022/23    2.513158  1.455263  1.057895
2023/24    2.644737  1.484211  1.160526
2024/25    2.618421  1.452632  1.165789
2025/26    2.694737  1.573684  1.121053

In [62]:
df_combined["HomeWin"] = (df_combined["FTR"] == "H").astype(int)
df_combined["AwayWin"] = (df_combined["FTR"] == "A").astype(int)
df_combined["Draw"] = (df_combined["FTR"] == "D").astype(int)

print(f"Media de victorias: {df_combined['HomeWin'].mean():.1%} locales, {df_combined['AwayWin'].mean():.1%} visitantes, {df_combined['Draw'].mean():.1%} empates")

Media de victorias: 45.8% locales, 28.6% visitantes, 25.6% empates

In [64]:
season_stats = df_combined.groupby("Season")[["TotalGoals", "FTHG", "FTAG", "HomeWin", "AwayWin", "Draw"]].mean()
print(season_stats.round(3))

         TotalGoals   FTHG   FTAG  HomeWin  AwayWin   Draw
Season
2013/14       2.750  1.632  1.118    0.471    0.303  0.226
2014/15       2.655  1.537  1.118    0.450    0.311  0.239
2015/16       2.745  1.618  1.126    0.482    0.276  0.242
2016/17       2.942  1.663  1.279    0.476    0.289  0.234
2017/18       2.695  1.547  1.147    0.471    0.303  0.226
2018/19       2.587  1.453  1.134    0.442    0.268  0.289
2019/20       2.479  1.437  1.042    0.458    0.266  0.276
2020/21       2.508  1.368  1.139    0.416    0.297  0.287
2021/22       2.503  1.421  1.082    0.434    0.274  0.292
2022/23       2.513  1.455  1.058    0.479    0.287  0.234
2023/24       2.645  1.484  1.161    0.439    0.279  0.282
2024/25       2.618  1.453  1.166    0.445    0.300  0.255
2025/26       2.695  1.574  1.121    0.489    0.266  0.245

In [66]:
df_teams = df_combined["HomeTeam"].unique()
print(f"Equipos únicos: {len(df_teams)}")
print(df_teams)

Equipos únicos: 32
<StringArray>
[   'Sociedad',    'Valencia',  'Valladolid',   'Barcelona',     'Osasuna',
 'Real Madrid',     'Sevilla',     'Almeria',       'Celta',   'Vallecano',
  'Ath Bilbao',      'Getafe',       'Elche',     'Espanol',  'Villarreal',
  'Ath Madrid',       'Betis',     'Levante',      'Malaga',     'Granada',
       'Eibar',     'Cordoba',   'La Coruna',    'Sp Gijon',  'Las Palmas',
     'Leganes',      'Alaves',      'Girona',      'Huesca',    'Mallorca',
       'Cadiz',      'Oviedo']
Length: 32, dtype: str

There are 2 new columns (TotalGoals & Season) that have been created to analyze the percentaje of home/away wins & the number of goals

## 3. Missing values in match statistics

In [68]:
df_null = df_combined[["HS", "AS", "HST", "AST", "HC", "AC", "HY", "AY", "HR", "AR"]].isnull().sum()
print("Valores missing por columna:")
print(df_null)

Valores missing por columna:
HS     0
AS     0
HST    0
AST    0
HC     0
AC     0
HY     0
AY     0
HR     0
AR     0
dtype: int64

There are no missing values, so thats perfect for the project